public class Constants {
    
    public static final string Discovery_Error = System.Label.Discovery_Error;
    public static final string DiscoveryDetails_Error = 'Please fill all discovery related details!!.';
    public static final string InternalDemo_Error = System.Label.InternalDemo_Error;
    public static final string DryRun_Error = System.Label.DryRun_Error;
    public static final string ClientDemo_Error = System.Label.ClientDemo_Error;
    public static final string AEProposal_Error = System.Label.AEProposal_Error;
    public static final string UploadProposal_Error = System.Label.UploadProposal_Error;
    public static final string SubmitProposal_Error = System.Label.SubmitProposal_Error;
     public static final String DiscDemoDate_Error = System.Label.DiscDemoDate_Error;
    public static final String Request_TimeOut = System.Label.Request_TimeOut;

    
}